export const roles = [
  {
    slug: "truck-dispatcher",
    title: "Truck Dispatcher",
    type: "Full-Time",
    location: "Remote (US)",
    department: "Dispatch",
    summary: "Manage a dedicated book of carriers booking freight, negotiating rates, and handling live support day to day.",
    responsibilities: [
      "Source and negotiate freight for a dedicated book of 15–25 carriers",
      "Track lane rate averages and push back on lowball broker offers",
      "Handle live support calls for breakdowns, detention, and reroutes",
      "File rate confirmations, BOLs, and same-day invoices",
    ],
    requirements: [
      "1+ years of trucking dispatch or brokerage experience",
      "Comfortable on the phone for extended periods daily",
      "Familiarity with DAT or Truckstop load boards",
      "Reliable internet and a quiet remote work setup",
    ],
  },
  {
    slug: "broker-relations-specialist",
    title: "Broker Relations Specialist",
    type: "Full-Time",
    location: "Remote (US)",
    department: "Partnerships",
    summary: "Build and maintain broker relationships that unlock repeat, higher-paying freight for our carrier network.",
    responsibilities: [
      "Maintain ongoing relationships with repeat-lane freight brokers",
      "Track carrier performance data to match reliability with priority freight",
      "Resolve broker-side disputes on behalf of carriers",
      "Identify new broker partnerships in underserved lanes",
    ],
    requirements: [
      "2+ years in freight brokerage or carrier sales",
      "Strong relationship-management instincts",
      "Comfortable negotiating and holding firm on rate terms",
      "Experience with TMS or CRM platforms a plus",
    ],
  },
  {
    slug: "compliance-coordinator",
    title: "Compliance Coordinator",
    type: "Full-Time",
    location: "Remote (US)",
    department: "Compliance",
    summary: "Handle permits, IFTA guidance, and pre-trip compliance checks across our carrier fleet.",
    responsibilities: [
      "Coordinate oversize and overweight permits ahead of dispatch",
      "Run pre-trip compliance checks on load-specific documentation",
      "Track insurance certificate expirations across the carrier network",
      "Support carriers with IFTA tracking questions",
    ],
    requirements: [
      "Experience in DOT or FMCSA compliance, carrier-side or brokerage-side",
      "Detail-oriented with strong documentation habits",
      "Familiarity with state-by-state permit requirements",
      "Clear written and verbal communication",
    ],
  },
  {
    slug: "onboarding-specialist",
    title: "Onboarding Specialist",
    type: "Part-Time",
    location: "Remote (US)",
    department: "Carrier Success",
    summary: "Guide new carriers through account setup and get them dispatched on their first load fast.",
    responsibilities: [
      "Walk new carriers through MC authority and insurance verification",
      "Capture equipment, lane, and home-time preferences accurately",
      "Coordinate with dispatch to book a carrier's first load within 48 hours",
      "Run 90-day check-ins with newly onboarded carriers",
    ],
    requirements: [
      "Strong customer-facing communication skills",
      "Comfortable working independently in a remote setting",
      "Trucking industry familiarity preferred, not required",
      "Organized, process-driven approach to follow-up",
    ],
  },
  {
    slug: "finance-factoring-associate",
    title: "Finance & Factoring Associate",
    type: "Full-Time",
    location: "Remote (US)",
    department: "Finance",
    summary: "Support same-day invoicing and factoring coordination so carriers get paid without delay.",
    responsibilities: [
      "Submit same-day invoices formatted to each carrier's factoring company",
      "Resolve documentation discrepancies before they delay funding",
      "Track funding timelines and flag delays proactively",
      "Advise carriers on whether factoring fits their cash-flow needs",
    ],
    requirements: [
      "Experience in freight factoring, billing, or accounts receivable",
      "Comfortable working across multiple factoring company systems",
      "Sharp attention to detail on documentation accuracy",
      "Clear, proactive communicator",
    ],
  },
];
