export const fleet = [
  {
    slug: "dry-van",
    name: "Dry Van",
    tag: "Most Versatile",
    tagline: "The workhorse of freight general commodities, palletized goods, and retail freight across nearly every lane in the network.",
    rating: "4.9",
    loads: "3.2K",
    tilt: -6,
    image: "/dryvan.jpeg",
    heroImage: "/dryvanhero.jpg",
    gallery: [
      "/dryvangallery1.jpg",
      "/dryvangallery2.jpg",
    ],
    intro:
      "Dry van is the backbone of American freight. An enclosed trailer that protects general commodities from weather while staying compatible with nearly every loading dock in the country. If you're new to dispatch or want the widest possible freight pool, dry van is where most carriers start.",
    stats: [
      ["Avg Rate", "$2.85/mi"],
      ["Avg Load Length", "620 mi"],
      ["Demand", "High"],
    ],
    specs: [
      { label: "Trailer Length", value: "53 ft" },
      { label: "Max Payload", value: "45,000 lbs" },
      { label: "Interior Height", value: "110 in" },
      { label: "Door Type", value: "Swing or Roll-Up" },
    ],
    uses: ["Retail & consumer goods", "Palletized freight", "Packaged food (non-perishable)", "Furniture & appliances", "Paper products & packaging", "General manufacturing goods"],
    howWeHelp: [
      { title: "Widest Freight Pool", copy: "Dry van has the largest volume of available loads of any equipment type, so your truck rarely sits idle waiting on the next booking." },
      { title: "Dock-Ready Matching", copy: "We match loads to trailers with the right door type and height clearance for each shipper's dock before you ever arrive." },
      { title: "Drop & Hook Priority", copy: "Where available, we prioritize drop-and-hook freight over live loads to keep your clock moving." },
      { title: "Backhaul Planning", copy: "Dry van's broad lane coverage makes backhaul freight easy to line up, minimizing empty miles on the return leg." },
    ],
    howItWorks: [
      { step: "01", title: "Equipment Check", copy: "We confirm your trailer specs: length, door type, height match what shippers require for your target lanes." },
      { step: "02", title: "Load Matching", copy: "Your dispatcher sources dry van freight across load boards and broker relationships matched to your lanes." },
      { step: "03", title: "Dock Coordination", copy: "Pickup and delivery windows are confirmed with the shipper's dock hours before you're dispatched." },
      { step: "04", title: "Delivery & Documentation", copy: "BOL is verified at delivery and invoicing goes out same-day." },
    ],
  },
  {
    slug: "reefer",
    name: "Reefer",
    tag: "Temperature Controlled",
    tagline: "Perishables, pharmaceuticals, and produce that can't wait reefer freight pays a premium for the added responsibility of temperature control.",
    rating: "4.8",
    loads: "1.9K",
    tilt: 4,
    image: "/reefer.jpeg",
    heroImage: "/reeferhero.jpg",
    gallery: [
      "/reefergallery1.jpg",
      "/reefergallery2.jpg",
    ],
    intro:
      "Reefer trailers carry a built-in refrigeration unit that holds precise temperatures for perishable freight produce, dairy, meat, pharmaceuticals cargo that spoils or loses value the moment the cold chain breaks. It pays more than dry van, but it demands more precision.",
    stats: [
      ["Avg Rate", "$3.15/mi"],
      ["Avg Load Length", "540 mi"],
      ["Demand", "High"],
    ],
    specs: [
      { label: "Trailer Length", value: "53 ft" },
      { label: "Max Payload", value: "43,500 lbs" },
      { label: "Temp Range", value: "-20°F to 70°F" },
      { label: "Fuel Reserve Needed", value: "Reefer Unit Diesel" },
    ],
    uses: ["Fresh produce", "Dairy & frozen goods", "Meat & seafood", "Pharmaceuticals", "Floral shipments", "Beverages requiring cold chain"],
    howWeHelp: [
      { title: "Cold Chain Verification", copy: "We confirm temperature requirements and pre-cool instructions with the shipper before pickup, so nothing gets flagged at delivery." },
      { title: "Premium Rate Negotiation", copy: "Reefer freight commands a rate premium. We make sure that premium actually lands in your rate confirmation." },
      { title: "Reefer Fuel Planning", copy: "Routes account for reefer unit fuel consumption separately from tractor fuel, so you're never caught short mid-route." },
      { title: "Detention Protection", copy: "Temperature-sensitive freight often means longer dock waits. We track detention aggressively on every reefer load." },
    ],
    howItWorks: [
      { step: "01", title: "Temp Requirements Confirmed", copy: "Exact temperature range and pre-cool requirements are verified with the shipper before booking." },
      { step: "02", title: "Load Matching", copy: "Freight is sourced from brokers and shippers who specifically need certified reefer capacity." },
      { step: "03", title: "In-Transit Monitoring", copy: "We stay in contact during transit to confirm the reefer unit is holding steady, especially on longer hauls." },
      { step: "04", title: "Delivery & Documentation", copy: "Temperature logs are verified alongside the BOL to protect you from disputed claims." },
    ],
  },
  {
    slug: "flatbed",
    name: "Flatbed",
    tag: "Heavy & Oversized",
    tagline: "Steel, lumber, machinery, and oversized loads flatbed carriers get priority permit support and route planning from our compliance desk.",
    rating: "4.9",
    loads: "1.4K",
    tilt: -3,
    image: "/flatbed.jpg",
    heroImage: "/flatbed.jpg",
    gallery: [
      "/flatbedgallery1.jpg",
      "/flatbed.jpg",
    ],
    intro:
      "Flatbed trailers have no walls or roof freight is secured with chains, straps, and tarps instead of being enclosed. That openness makes flatbed the only practical option for oversized, heavy, or awkwardly-shaped freight like steel, lumber, and construction equipment.",
    stats: [
      ["Avg Rate", "$3.05/mi"],
      ["Avg Load Length", "480 mi"],
      ["Demand", "Steady"],
    ],
    specs: [
      { label: "Trailer Length", value: "48–53 ft" },
      { label: "Max Payload", value: "48,000 lbs" },
      { label: "Deck Height", value: "60 in (standard)" },
      { label: "Securement", value: "Chains, Straps, Tarps" },
    ],
    uses: ["Steel coils & beams", "Lumber & building materials", "Heavy machinery", "Construction equipment", "Pipe & industrial materials", "Oversized/overweight freight"],
    howWeHelp: [
      { title: "Permit Coordination", copy: "Oversize and overweight permits are secured ahead of dispatch by our compliance desk, not scrambled together last minute." },
      { title: "Securement Guidance", copy: "We confirm chain, strap, and tarp requirements for each specific load type before you arrive to load." },
      { title: "Route Planning For Clearance", copy: "Routes account for bridge heights, weight restrictions, and state-by-state oversize regulations." },
      { title: "Specialized Broker Access", copy: "Flatbed freight often comes through relationships, not open boards. We maintain those connections directly." },
    ],
    howItWorks: [
      { step: "01", title: "Load & Securement Review", copy: "Freight dimensions and weight are reviewed to confirm chain, strap, and tarp requirements." },
      { step: "02", title: "Permit Check", copy: "Any oversize or overweight permits needed for the route are secured before the load is confirmed." },
      { step: "03", title: "Route Clearance Planning", copy: "Routes are mapped around bridge and weight restrictions specific to the load's dimensions." },
      { step: "04", title: "Delivery & Documentation", copy: "Delivery is confirmed and any accessorial charges for tarping or securement are documented." },
    ],
  },
  {
    slug: "power-only",
    name: "Power Only",
    tag: "Maximum Flexibility",
    tagline: "Just the tractor, Drop and hook freight that keeps you moving without waiting on a live load or unload.",
    rating: "4.7",
    loads: "980",
    tilt: 7,
    image: "/poweronly.jpg",
    heroImage: "/poweronly.jpg",
    gallery: [
      "/poweronlygallery1.jpg",
      "/poweronlygallery2.jpg",
    ],
    intro:
      "Power only means you provide the tractor and pull a trailer that already belongs to the shipper, broker, or another carrier, Usually a drop-and-hook setup. It's the most flexible equipment type, letting you move between freight types without owning your own trailer.",
    stats: [
      ["Avg Rate", "$2.70/mi"],
      ["Avg Load Length", "410 mi"],
      ["Demand", "Growing"],
    ],
    specs: [
      { label: "Trailer Provided By", value: "Shipper / Broker" },
      { label: "Typical Setup", value: "Drop & Hook" },
      { label: "Tractor Requirement", value: "Standard Day Cab or Sleeper" },
      { label: "Live Load Frequency", value: "Rare" },
    ],
    uses: ["Retail drop-trailer programs", "Intermodal drayage support", "Overflow capacity for shippers", "E-commerce fulfillment freight", "Regional short-haul freight", "Trailer relocation runs"],
    howWeHelp: [
      { title: "Drop-Trailer Program Access", copy: "We maintain relationships with shippers running dedicated drop-trailer programs, which is where the best power-only freight lives." },
      { title: "Minimal Dwell Time", copy: "Because there's no live load or unload, power-only freight moves through your schedule faster. We prioritize these tight-turnaround loads." },
      { title: "Equipment-Free Flexibility", copy: "Without a trailer to maintain, you can pivot between freight types more easily. We help you find the mix that pays best." },
      { title: "Trailer Condition Verification", copy: "We confirm trailer condition and tire status with the shipper before you hook, so you're not liable for pre-existing damage." },
    ],
    howItWorks: [
      { step: "01", title: "Program Matching", copy: "We match you to shippers and brokers running drop-and-hook power-only freight in your preferred lanes." },
      { step: "02", title: "Trailer Handoff Confirmation", copy: "Trailer location, condition, and hookup details are confirmed before you arrive." },
      { step: "03", title: "Quick Turn Dispatch", copy: "Because there's no wait on loading or unloading, your next load is often lined up before you've dropped the current one." },
      { step: "04", title: "Delivery & Documentation", copy: "Drop location is confirmed and paperwork is filed same-day." },
    ],
  },
  {
    slug: "step-deck",
    name: "Step Deck",
    tag: "Tall & Heavy Freight",
    tagline: "A lowered rear deck that clears taller freight under bridge restrictions the go-to for equipment flatbed can't quite handle.",
    rating: "4.8",
    loads: "620",
    tilt: -5,
    image: "/stepdeck.jpg",
    heroImage: "/stepdeck.jpg",
    gallery: [
      "/Stepdeckgallery1.jpg",
      "/Stepdeckgallery2.jpg",
    ],
    intro:
      "Step deck (also called drop deck) trailers have two levels. A higher front deck over the tractor and a lower main deck behind it. That drop in height means taller freight can clear bridges and overpasses that would be illegal on a standard flatbed.",
    stats: [
      ["Avg Rate", "$3.20/mi"],
      ["Avg Load Length", "460 mi"],
      ["Demand", "Steady"],
    ],
    specs: [
      { label: "Trailer Length", value: "48–53 ft" },
      { label: "Max Payload", value: "48,000 lbs" },
      { label: "Lower Deck Height", value: "36–40 in" },
      { label: "Max Freight Height", value: "Up to 10 ft" },
    ],
    uses: ["Construction & farm equipment", "Tall machinery", "Manufactured housing components", "Industrial tanks", "Oversized crates", "Vehicles & equipment on wheels"],
    howWeHelp: [
      { title: "Height Clearance Planning", copy: "Routes are mapped specifically around bridge clearances for your freight's exact height, not a general estimate." },
      { title: "Ramp & Loading Coordination", copy: "For equipment that drives on, we confirm ramp availability and loading procedure with the shipper in advance." },
      { title: "Specialized Rate Negotiation", copy: "Step deck freight is less common than standard flatbed, and we make sure that specialization is reflected in the rate." },
      { title: "Permit & Compliance Support", copy: "Height and weight permits are handled by our compliance desk before the load is ever confirmed." },
    ],
    howItWorks: [
      { step: "01", title: "Freight Height Review", copy: "Exact freight dimensions are confirmed to verify step deck is the right equipment for the load." },
      { step: "02", title: "Route & Clearance Mapping", copy: "Routes are planned around confirmed bridge and overpass clearances for the load's height." },
      { step: "03", title: "Loading Coordination", copy: "Ramp or crane-loading logistics are confirmed with the shipper ahead of pickup." },
      { step: "04", title: "Delivery & Documentation", copy: "Delivery is confirmed and any specialized handling charges are documented same-day." },
    ],
  },
  {
    slug: "hotshot",
    name: "Hotshot",
    tag: "Fast & Time-Sensitive",
    tagline: "Smaller loads, tighter deadlines. Hotshot trucking moves urgent freight fast using a pickup-and-trailer setup instead of a full semi.",
    rating: "4.7",
    loads: "740",
    tilt: 5,
    image: "/hotshot.jpg",
    heroImage: "/hotshot.jpg",
    gallery: [
      "/hotshotgallery1.jpg",
      "/hotshotgallery2.jpg",
    ],
    intro:
      "Hotshot trucking uses a heavy-duty pickup truck pulling a gooseneck or bumper-pull trailer, built for smaller, time-sensitive loads that don't need a full 53-foot trailer. It's a common entry point for owner-operators and a fast option for shippers who need freight moved now.",
    stats: [
      ["Avg Rate", "$2.55/mi"],
      ["Avg Load Length", "290 mi"],
      ["Demand", "Growing"],
    ],
    specs: [
      { label: "Trailer Type", value: "Gooseneck or Bumper-Pull" },
      { label: "Max Payload", value: "Up to 16,500 lbs" },
      { label: "Truck Requirement", value: "Class 3–5 Pickup" },
      { label: "Typical Trailer Length", value: "20–40 ft" },
    ],
    uses: ["Emergency equipment parts", "Construction equipment", "Farm & agricultural equipment", "Time-critical LTL freight", "Vehicle transport", "Oilfield equipment"],
    howWeHelp: [
      { title: "Urgent Freight Matching", copy: "We prioritize time-sensitive loads that pay a premium specifically because they need to move fast." },
      { title: "Weight & Capacity Verification", copy: "Every load is checked against your specific trailer's rated capacity before you're dispatched." },
      { title: "Flexible Scheduling", copy: "Hotshot freight often books same-day. We keep your availability visible to brokers who need fast pickup." },
      { title: "Regional Lane Focus", copy: "We build hotshot routes around regional lanes to keep runs short and turnaround fast." },
    ],
    howItWorks: [
      { step: "01", title: "Capacity Confirmation", copy: "Your specific truck and trailer rating are confirmed against the load's weight before booking." },
      { step: "02", title: "Urgent Load Matching", copy: "Time-sensitive freight is sourced and matched to your available pickup window." },
      { step: "03", title: "Fast Turnaround Dispatch", copy: "Because runs are shorter, your next load is often lined up the same day." },
      { step: "04", title: "Delivery & Documentation", copy: "Delivery is confirmed quickly and invoicing goes out same-day, matching the pace of the freight itself." },
    ],
  },
];

export function getTruckBySlug(slug) {
  return fleet.find((f) => f.slug === slug);
}
