export const plans = [
  {
    slug: "starter",
    name: "Starter Plan",
    rate: "4.99%",
    tagline: "For owner-operators who want core dispatch support without the extras.",
    cta: "Get Started",
    formType: "client",
    highlight: false,
    features: [
      "One dedicated dispatcher",
      "Load booking & rate negotiation",
      "Standard business-hours support",
      "Same-day invoicing",
      "Basic route planning",
    ],
    notIncluded: ["24/7 live emergency radio", "Priority broker relationships", "Dedicated compliance support", "Fleet-wide performance reporting"],
  },
  {
    slug: "premium",
    name: "Premium Plan",
    rate: "9.99%",
    tagline: "Full-coverage dispatch for carriers who want everything handled.",
    cta: "Get Started",
    formType: "client",
    highlight: true,
    features: [
      "Everything in Starter, plus:",
      "24/7 live emergency radio support",
      "Priority broker relationships & first-look freight",
      "Dedicated compliance & permit support",
      "Advanced fuel & route optimization",
      "Factoring coordination & same-day submission",
      "Fleet-wide performance reporting",
    ],
    notIncluded: [],
  },
  {
    slug: "enterprise",
    name: "Enterprise Plan",
    rate: "Custom",
    tagline: "For fleets of 10+ trucks needing a fully custom dispatch structure.",
    cta: "Contact Sales",
    formType: "sales",
    highlight: false,
    features: [
      "Everything in Premium, plus:",
      "Custom rate structure by volume",
      "Dedicated account manager",
      "Integration with your TMS",
      "Quarterly performance reviews",
      "Custom SLAs & reporting cadence",
    ],
    notIncluded: [],
  },
];

export const pricingDetails = [
  { title: "No Setup Fees", copy: "Onboarding is free on every plan. You only pay the percentage on loads we actually book." },
  { title: "No Long-Term Contracts", copy: "Cancel anytime on Starter or Premium. We keep carriers by earning it, not by locking them in." },
  { title: "Transparent Deductions", copy: "Our fee applies only to the base linehaul rate detention, layover, and accessorial pay are always 100% yours." },
  { title: "Upgrade Anytime", copy: "Start on Starter and move to Premium the moment you need 24/7 coverage or priority broker access." },
];
