export const team = [
  {
    slug: "moazzam",
    name: "Moazzam",
    role: "Founder & CEO",
    department: "Administration",
    image: "/moazzam.png",
    joined: "2019",
    bio: "Moazzam spent six years dispatching for a regional carrier before founding JarveX Solutions in 2019, frustrated by how often owner-operators were treated as a number instead of a partner.",
    longBio: [
      "Before JarveX Solutions, Moazzam ran dispatch for a 10-truck regional fleet, where the same complaint kept surfacing from owner-operators: nobody on the other end of the phone actually knew their truck. Rates felt arbitrary, paperwork sat for days, and the moment something went wrong, carriers were on their own.",
      "JarveX Solutions started as a two-person operation working out of a spare office, with one rule that hasn't changed since: every carrier gets a dispatcher who actually knows them, not a rotating call queue.",
      "Today Moazzam oversees strategy and partnerships, but still takes dispatch calls during peak season. Habit the team has stopped trying to talk him out of.",
    ],
    specialties: ["Company Strategy", "Broker Partnerships", "Carrier Relations"],
    quote: "A carrier's truck is their whole business. We built JarveX Solutions around never forgetting that.",
    highlights: [
      { year: "2019", title: "Joined Moaz Group of Companies", copy: "Brought JarveX Solutions under a larger group structure to scale support without losing the personal model." },
      { year: "2020", title: "Founded JarveX Solutions", copy: "Started with two dispatchers and one owner-operator in the network." },
      { year: "2021", title: "Crossed 100 Carriers", copy: "Expanded coverage into reefer and flatbed equipment for the first time." },
    ],
  },
  {
    slug: "marcus-lee",
    name: "Marcus Lee",
    role: "Senior Rate Negotiator",
    department: "Rates & Negotiation",
    image: "/marcuslee.png",
    joined: "2020",
    bio: "Marcus tracks lane-level rate data daily and has negotiated freight across nearly every major corridor in the country.",
    longBio: [
      "Marcus joined JarveX Solutions after five years as a broker-side rate analyst, which gives him a rare advantage. He knows exactly how brokers build their numbers before he ever picks up the phone.",
      "He built the lane-rate tracking process the whole dispatch team now uses, checking current averages against every incoming offer before a single word is negotiated.",
      "Carriers who work with Marcus often mention the same thing: he doesn't just accept the first counteroffer, and he explains why a rate is fair instead of just telling them it is.",
    ],
    specialties: ["Rate Benchmarking", "Broker Negotiation", "Lane Analysis"],
    quote: "The best negotiation is the one where you already know the answer before you ask the question.",
    highlights: [
      { year: "2020", title: "Joined JarveX Solutions", copy: "Brought five years of broker-side rate analysis experience to the dispatch desk." },
      { year: "2022", title: "Built the Rate Benchmarking System", copy: "Created the lane-average tracking process used across the entire dispatch team today." },
      { year: "2025", title: "1,000th Negotiated Load", copy: "Crossed a personal milestone of 1,000 individually negotiated rate confirmations." },
    ],
  },
  {
    slug: "thomas-rodriguez",
    name: "Thomas Rodriguez",
    role: "Head of Broker Relations",
    department: "Broker & Shipper Relations",
    image: "/thomasrodriguez.png",
    joined: "2020",
    bio: "Thomas manages the broker and shipper relationships that give JarveX Solutions carriers first-look access to repeat freight.",
    longBio: [
      "Thomas's background is in freight brokerage, which means he built his JarveX Solutions relationships from the other side of the table first. He knows exactly what makes a broker trust a carrier enough to call them directly.",
      "He personally maintains relationships with dozens of repeat-lane brokers, tracking which carriers perform best on which lanes so freight gets matched intentionally, not randomly.",
      "His rule for the team: a broker should never have to wonder if a JarveX Solutions truck will show up on time. That reputation is the whole value of the relationship.",
    ],
    specialties: ["Broker Relationships", "Repeat-Lane Freight", "Carrier Reputation Management"],
    quote: "Reputation is the only currency that actually compounds in this industry.",
    highlights: [
      { year: "2020", title: "Joined JarveX Solutions", copy: "Came from a brokerage background managing carrier relationships from the other side." },
      { year: "2023", title: "50+ Repeat Broker Partners", copy: "Built a network of brokers who call JarveX Solutions carriers directly for repeat freight." },
      { year: "2026", title: "Led First-Look Program Launch", copy: "Formalized the performance-tracking system that unlocks priority freight for reliable carriers." },
    ],
  },
  {
    slug: "harry-watson",
    name: "Harry Watson",
    role: "Compliance Director",
    department: "Compliance & Permits",
    image: "/harrywatson.png",
    joined: "2021",
    bio: "Harry runs the compliance desk permits, IFTA guidance, and pre-trip checks that keep carriers out of trouble at the scale house.",
    longBio: [
      "Harry spent four years as a compliance officer for a mid-size carrier before joining JarveX Solutions, and he brought a simple philosophy with him: compliance problems should be caught on a Tuesday afternoon, not at a weigh station on a Friday night.",
      "He built the pre-trip compliance checklist every JarveX Solutions dispatcher now runs before a load is confirmed, covering everything from oversize permits to insurance certificate expiration dates.",
      "Carriers who've had a rough experience with compliance elsewhere tend to become Harry's biggest advocates once they see how much friction disappears with someone tracking it proactively.",
    ],
    specialties: ["IFTA & Permits", "Pre-Trip Compliance", "Audit Preparation"],
    quote: "Every compliance problem we prevent is a Friday night that goes smoothly instead of sideways.",
    highlights: [
      { year: "2021", title: "Joined JarveX Solutions", copy: "Brought four years of carrier-side compliance experience to build out the desk." },
      { year: "2023", title: "Built the Pre-Trip Checklist", copy: "Standardized the compliance review every load goes through before confirmation." },
      { year: "2025", title: "Zero Preventable Violations", copy: "Led a full year with zero preventable compliance violations across the carrier network." },
    ],
  },
  {
    slug: "leo-ferreira",
    name: "Leo Ferreira",
    role: "Route Planning Lead",
    department: "Route & Fuel Planning",
    image: "/leoferreira.png",
    joined: "2022",
    bio: "Leo plans routes around hours-of-service limits, fuel pricing, and delivery windows so carriers aren't guessing at a truck stop.",
    longBio: [
      "Leo drove flatbed for six years before moving into dispatch, which means every route he builds accounts for things a desk-only planner might missparking availability, realistic fuel stop timing, and the reality of a delivery window that looked fine on paper but isn't.",
      "He built JarveX Solutions fuel-stop optimization approach, weighing real-time pricing against detour distance to make sure a 'cheaper' stop is actually cheaper once the extra miles are counted.",
      "His flatbed background also makes him the go to for carriers navigating anything oversized or unusual. He is driven the exact problem most planners only read about.",
    ],
    specialties: ["HOS-Aware Routing", "Fuel Optimization", "Flatbed & Oversized Freight"],
    quote: "A route only looks efficient on a map. It has to actually work at a truck stop at 2 AM.",
    highlights: [
      { year: "2022", title: "Joined JarveX Solutions", copy: "Moved from six years driving flatbed into full-time route planning." },
      { year: "2023", title: "Built Fuel-Stop Optimization", copy: "Created the routing logic that weighs fuel pricing against detour distance in real time." },
      { year: "2025", title: "98.6% On-Time Milestone", copy: "Routing improvements contributed directly to the network's current on-time delivery rate." },
    ],
  },
  {
    slug: "sam-alvarez",
    name: "Sam Alvarez",
    role: "Carrier Success Manager",
    department: "Carrier Support",
    image: "/samalvarez.png",
    joined: "2022",
    bio: "Sam is usually the first voice a new carrier hears and the one who checks in months later just to see how things are going.",
    longBio: [
      "Sam runs point on onboarding, which at JarveX Solutions means more than paperwork. It means understanding a carrier's preferred lanes, home time needs, and equipment quirks well enough to set expectations honestly from day one.",
      "He also owns the 90-day check-in process, a habit most dispatch companies skip entirely: a real conversation with every new carrier about what's working and what isn't, without waiting for a complaint to surface first.",
      "Carriers frequently mention that Sam remembers small details from onboarding months later, This kind of thing that makes a flat-fee service feel like a relationship instead of a transaction.",
    ],
    specialties: ["Carrier Onboarding", "Relationship Management", "Retention"],
    quote: "The best account management is checking in before something goes wrong, not after.",
    highlights: [
      { year: "2022", title: "Joined JarveX Solutions", copy: "Took over onboarding and built it into a structured, same-day process." },
      { year: "2023", title: "Launched 90-Day Check-Ins", copy: "Introduced proactive carrier check-ins that now happen for every account." },
      { year: "2026", title: "300th Carrier Onboarded", copy: "Personally onboarded the network's 300th active carrier." },
    ],
  },
  {
    slug: "david-kim",
    name: "David Kim",
    role: "Finance & Factoring Advisor",
    department: "Billing & Factoring",
    image: "/davidkim.png",
    joined: "2023",
    bio: "David coordinates directly with carriers' factoring companies so invoices move fast and cash flow stays predictable.",
    longBio: [
      "David's background in freight factoring means he understands both sides of the invoice, What carriers need and what factoring companies require to fund quickly.",
      "He built the same-day invoicing workflow now standard across JarveX Solutions, formatting every document to match a carrier's specific factoring company on the day a load delivers.",
      "For carriers not using a factoring company, he's often the first person to walk them through whether it actually makes financial sense for their situation not just sell them on it.",
    ],
    specialties: ["Factoring Coordination", "Invoice Processing", "Carrier Financial Planning"],
    quote: "Cash flow problems are usually paperwork problems wearing a disguise.",
    highlights: [
      { year: "2023", title: "Joined JarveX Solutions", copy: "Brought factoring-industry experience to formalize the finance desk." },
      { year: "2024", title: "Built Same-Day Invoicing", copy: "Standardized same-day invoice submission across every carrier account." },
      { year: "2026", title: "Zero-Delay Funding Streak", copy: "Currently maintaining a multi-month streak with zero factoring-related funding delays." },
    ],
  },
  {
    slug: "peter-park",
    name: "Peter Park",
    role: "Head of Growth & Market Analysis",
    department: "Strategy",
    image: "/peterpark.png",
    joined: "2024",
    bio: "Peter tracks freight market trends so JarveX Solutions carriers know what's coming before it shows up in their rate confirmations.",
    longBio: [
      "Peter came from a logistics analytics firm, where he spent years modeling capacity and rate trends for large fleets. At JarveX Solutions, he applies that same rigor at a scale that actually helps individual owner-operators, not just enterprise accounts.",
      "He publishes regular market analysis for the JarveX Solutions blog and briefs the dispatch team on emerging trends, which lanes are tightening, which equipment types are seeing rate pressure, and where seasonal demand is shifting.",
      "His goal is simple: make sure JarveX Solutions carriers are never surprised by a market shift that the data already showed coming.",
    ],
    specialties: ["Market Analysis", "Capacity Forecasting", "Growth Strategy"],
    quote: "Most rate surprises aren't surprises at all, The data usually saw it coming weeks earlier.",
    highlights: [
      { year: "2024", title: "Joined JarveX Solutions", copy: "Brought enterprise level market analytics experience to a carrier-first dispatch model." },
      { year: "2025", title: "Launched Market Briefings", copy: "Started regular market analysis shared across the dispatch team and the blog." },
      { year: "2026", title: "Led Moaz Group Integration Planning", copy: "Helped shape JarveX Solutions' growth strategy as part of the wider Moaz Group of Companies." },
    ],
  },
];

export function getTeamMemberBySlug(slug) {
  return team.find((t) => t.slug === slug);
}
